### ISSUE TITLE
Chris is wrong at 6:30 of video

### ISSUE THREAD

**Issue by valeriyvan** [objcio/S01E80-swift-string-vs-nsstring#1]
@chriseidhof is wrong at 6:30 of video stating that in this case we have synchronized `textView.string` and `text` and we could safely force unwrap `let range = Range(nsRange, in: text)!` because we know range always exists.

Run app, move cursor to the very end of text view and start editing. Crash.

That's because, actually, `textView.string` and `text` are not synchronized. And that is because when text being view is edited it calls `textViewDidChangeSelection` delegate function first and then `textDidChange`. So, if text view is being edited, in `updateInfo` `textView.string` and `text` are out of sync.

To solve this, instead of `text` `textView.string` has to be used in `updateInfo`.

I have learnt one lesson out of this: force unwrap shouldn't be used even if you sure it's safe to force unwrap exact in this case. Because you might be wrong.

**Comment by chriseidhof** [comment]
Thanks @valeriyvan ! You're completely right. 

I do think the force unwrap is nice because exactly this: it crashes because the code is wrong in other places. With optional chaining, the bug might not surface. 

The code was not very well tested (at least not the editing part), we tried to focus on the unicode examples.
